name: CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod download
      - name: Build the application
        run: go build -o pgpockets ./cmd/pgpockets
    #   - name: Run tests
    #     run: go test ./...
      - name: Build Docker image
        run: docker build -t pgpockets:latest .
    #   - name: Push Docker image
    #     run: |
    #       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #       docker tag pgpockets:latest ${{ secrets.DOCKER_USERNAME }}/pgpockets:latest
    #       docker push ${{ secrets.DOCKER_USERNAME }}/pgpockets:latest
    #   - name: Deploy to server
    #     run: |
    #       ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
    #       docker pull ${{ secrets.DOCKER_USERNAME }}/pgpockets:latest
    #       docker stop pgpockets || true
    #       docker rm pgpockets || true
    #       docker run -d --name pgpockets -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/pgpockets:latest
    #       EOF
    #     env:
    #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #     shell: bash
    #   - name: Notify deployment success
    #     run: echo "Deployment successful!"
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     shell: bash
    #   - name: Send Slack notification
    #     run: |
    #       curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment successful!"}' $SLACK_WEBHOOK_URL
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     shell: bash 
